name: CI/CD Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: SSH-Agent starten
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Build & Deployment auf Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            # Verzeichnis erstellen oder hineingehen
            cd ~/webapp || git clone https://github.com/${{ github.repository }} ~/webapp && cd ~/webapp

            # Aktuellen Branch ziehen
            git checkout main
            git pull origin main

